const CONTAINERS = {
  '20ft': { name:'20ft Dry', l:5898, w:2352, h:2393, maxWeight:28200 },
  '40ft': { name:'40ft Dry', l:12032, w:2352, h:2393, maxWeight:26700 },
  '40hc': { name:'40ft High Cube', l:12032, w:2352, h:2698, maxWeight:26500 },
  '45hc': { name:'45ft High Cube', l:13556, w:2352, h:2698, maxWeight:27600 }
};
const COLORS = ['#16734f','#ff8a4c','#5a87ff','#c28b38','#8c6ad8','#e15d71','#43a6a1'];
const STRATEGIES={sequence:{label:'안전 우선'},hybrid:{label:'안전·폭 균형'},volume:{label:'공간 활용 우선'},width:{label:'폭 최적화'},balance:{label:'무게중심 우선'}};
const TRANSPORT_PROFILES={sea:{label:'해상',slender:1.35,column:1.7,minSides:3},combined:{label:'복합',slender:1.5,column:2,minSides:2},road:{label:'육상',slender:1.75,column:2.4,minSides:2}};
const currentTransportMode=()=>typeof document==='undefined'?'combined':$('transportMode')?.value||'combined';
let products = [];
let result = null;
let shipment = null;
let fieldResult = null;
let activeContainer = 0;
let camera = { yaw:-2.51, pitch:0.42, zoom:1 };
let viewMode = 'iso';
let visibleStep = 0;
let playTimer = null;
let threeView = null;
let showDunnage = true;
let showAirbags = true;
let showCog = false;
let simulationRunning = false;
const widthGapCache = new Map();
let packingWidths = [];
let packingWidthSignature = '';
let packingTypeCount = 0;
const $ = id => document.getElementById(id);
let messageResolver=null;
function showAppMessage(message,{title='안내',tone='info',confirmAction=false,actionLabel='확인',cancelLabel='취소'}={}){
  const dialog=$('messageDialog');
  if(dialog.open){dialog.close();messageResolver?.(false)}
  $('messageTitle').textContent=title;$('messageText').textContent=message;dialog.dataset.tone=tone;$('messageCancel').hidden=!confirmAction;$('messageCancel').textContent=cancelLabel;$('messageConfirm').textContent=actionLabel;
  return new Promise(resolve=>{const finish=value=>{messageResolver=null;dialog.close();resolve(value)};messageResolver=resolve;$('messageConfirm').onclick=()=>finish(true);$('messageCancel').onclick=()=>finish(false);dialog.oncancel=e=>{e.preventDefault();finish(false)};dialog.showModal()});
}
if(typeof window!=='undefined')window.showAppMessage=showAppMessage;

function init(){
  $('containerType').innerHTML = Object.entries(CONTAINERS).map(([k,c])=>`<option value="${k}">${c.name}</option>`).join('');
  bindEvents(); updateContainerSpec(); renderProducts(); resizeCanvas();
}
function bindEvents(){
  $('guideButton').onclick=()=>$('guideDialog').showModal();
  $('policyButton').onclick=()=>$('policyDialog').showModal();
  $('ctuButton').onclick=()=>$('ctuDialog').showModal();
  document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>switchTab(tab.dataset.tab));
  $('addProduct').onclick=addProduct;
  $('loadDemo').onclick=()=>$('sampleDialog').showModal();
  document.querySelectorAll('[data-sample]').forEach(button=>button.onclick=()=>loadDemo(+button.dataset.sample));
  $('containerType').onchange=()=>{updateContainerSpec();markSimulationChanged()};
  $('optimization').onchange=markSimulationChanged;
  $('transportMode').onchange=markSimulationChanged;
  $('recalculateList').onclick=simulate;
  $('recalculateOptions').onclick=simulate;
  $('fileInput').onchange=async e=>{await readFile(e.target.files[0]);e.target.value=''};
  $('downloadTemplate').onclick=downloadTemplate;
  $('exportPlan').onclick=exportPlan;
  $('exportPdf').onclick=exportPdf;
  $('toggleSequence').onclick=toggleSequence;
  $('toggleProducts').onclick=toggleProductList;
  $('viewIso').onclick=()=>setView('iso');$('viewTop').onclick=()=>setView('top');$('viewDoor').onclick=()=>setView('door');$('viewLeft').onclick=()=>setView('left');$('viewRight').onclick=()=>setView('right');
  $('viewCog').onclick=toggleCenterOfGravity;
  $('toggleDunnage').onclick=()=>toggleSecuringVisibility('dunnage');
  $('toggleAirbags').onclick=()=>toggleSecuringVisibility('airbags');
  $('resetView').onclick=()=>{camera={yaw:-2.51,pitch:0.42,zoom:1};setView('iso')};
  $('prevStep').onclick=()=>setStep(visibleStep-1);
  $('nextStep').onclick=()=>setStep(visibleStep+1);
  $('playSteps').onclick=togglePlayback;
  $('stepRange').oninput=e=>setStep(+e.target.value);
  const dz=$('dropzone'); ['dragenter','dragover'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add('drag')}));
  ['dragleave','drop'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.remove('drag')}));
  dz.addEventListener('drop',e=>readFile(e.dataTransfer.files[0]));
  let dragging=false,last={x:0,y:0}; const canvas=$('loadingCanvas');
  canvas.addEventListener('pointerdown',e=>{if(viewMode!=='iso')return;dragging=true;last={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)});
  canvas.addEventListener('pointermove',e=>{if(!dragging)return;camera.yaw+=(e.clientX-last.x)*.008;camera.pitch=Math.max(.1,Math.min(1.1,camera.pitch+(e.clientY-last.y)*.006));last={x:e.clientX,y:e.clientY};draw()});
  canvas.addEventListener('pointerup',()=>dragging=false);
  canvas.addEventListener('wheel',e=>{e.preventDefault();camera.zoom=Math.max(.55,Math.min(2,camera.zoom*(e.deltaY>0?.9:1.1)));draw()},{passive:false});
  window.addEventListener('resize',()=>{resizeCanvas();syncSequenceHeight()});
}
function switchTab(name){document.querySelectorAll('.tab').forEach(x=>{x.classList.toggle('active',x.dataset.tab===name);x.setAttribute('aria-selected',x.dataset.tab===name)});$('manualPane').classList.toggle('active',name==='manual');$('uploadPane').classList.toggle('active',name==='upload')}
function addProduct(){
  const topLoad=$('productMaxTopLoad').value,p={name:$('productName').value.trim(),group:$('productGroup').value.trim()||'기타',shape:$('productShape').value,qty:+$('productQty').value,l:+$('productLength').value,w:+$('productWidth').value,h:+$('productHeight').value,weight:+$('productWeight').value,maxTopLoadKg:topLoad===''?null:+topLoad,rotate:$('allowRotation').checked,fragile:$('fragile').checked};
  if(!p.name||[p.qty,p.l,p.w,p.h,p.weight].some(v=>!v||v<=0)||(p.maxTopLoadKg!=null&&(!Number.isFinite(p.maxTopLoadKg)||p.maxTopLoadKg<0))){showAppMessage('제품명과 수량, 규격, 중량, 상부 허용하중을 올바르게 입력해 주세요.',{title:'제품 정보를 확인해 주세요',tone:'warning'});return}
  p.id=Date.now()+Math.random(); p.color=COLORS[products.length%COLORS.length];products.push(p);renderProducts();window.loadwiseStorage?.suggestName(`${p.name} 적재`);
}
const SAMPLE_SETS={
  1:{name:'혼합 화물',products:[{name:'산업용 펌프',group:'기계류',shape:'box',qty:4,l:1200,w:800,h:900,weight:420,maxTopLoadKg:2000,rotate:true,fragile:false},{name:'제어반',group:'전기장비',shape:'box',qty:6,l:900,w:600,h:1100,weight:180,maxTopLoadKg:0,rotate:false,fragile:true},{name:'케이블 드럼',group:'부품',shape:'cylinder',qty:10,l:900,w:900,h:700,weight:310,maxTopLoadKg:1200,rotate:false,fragile:false},{name:'필터 박스',group:'소모품',shape:'box',qty:16,l:600,w:500,h:450,weight:52,maxTopLoadKg:500,rotate:true,fragile:false}]},
  2:{name:'단일 규격 반복',products:[{name:'표준 수출박스',group:'포장화물',shape:'box',qty:42,l:1000,w:780,h:720,weight:145,maxTopLoadKg:1000,rotate:false,fragile:false}]},
  3:{name:'크기 차이 비교',products:[{name:'대형 설비박스',group:'설비',shape:'box',qty:3,l:1800,w:1100,h:1250,weight:780,maxTopLoadKg:3000,rotate:false,fragile:false},{name:'중형 부품박스',group:'부품',shape:'box',qty:10,l:1000,w:720,h:650,weight:165,maxTopLoadKg:800,rotate:true,fragile:false},{name:'소형 완충박스',group:'소모품',shape:'box',qty:24,l:480,w:380,h:320,weight:28,maxTopLoadKg:250,rotate:true,fragile:false}]}
};
function loadDemo(number=1){const sample=SAMPLE_SETS[number]||SAMPLE_SETS[1];products=sample.products.map((p,i)=>({...p,id:Date.now()+i,color:COLORS[i%COLORS.length]}));$('sampleDialog').close();renderProducts();window.loadwiseStorage?.suggestName(`샘플 ${number} · ${sample.name}`);simulate();document.querySelector('#planner').scrollIntoView({behavior:'smooth'})}
function renderProducts(){
  const total=products.reduce((s,p)=>s+p.qty,0);$('productCount').textContent=`(${products.length}개 품목 · ${total}박스)`;$('recalculateList').disabled=!products.length;$('recalculateOptions').disabled=!products.length;
  $('productList').innerHTML=products.length?products.map((p,i)=>`<div class="product-item"><span class="product-color" style="background:${p.color};border-radius:${p.shape==='cylinder'?'50%':'5px'}"></span><div><div class="product-title-row"><strong>${esc(p.name)}</strong><div class="qty-stepper" aria-label="${esc(p.name)} 수량"><span>수량</span><input type="number" min="1" step="1" value="${p.qty}" data-qty-input="${i}" aria-label="${esc(p.name)} 수량 직접 입력"><span class="qty-arrows"><button type="button" data-qty-up="${i}" aria-label="수량 증가">▲</button><button type="button" data-qty-down="${i}" aria-label="수량 감소" ${p.qty<=1?'disabled':''}>▼</button></span></div></div><small>${esc(p.group)} · ${p.shape==='cylinder'?'원통형':'박스형'} · ${p.l}×${p.w}×${p.h} mm · ${p.weight} kg${Number.isFinite(p.maxTopLoadKg)?` · 상부 허용 ${p.maxTopLoadKg} kg`:''}</small><div class="product-options"><label><input type="checkbox" data-lay="${i}" ${p.rotate?'checked':''}> 눕힘 허용</label><label><input type="checkbox" data-fragile="${i}" ${p.fragile?'checked':''}> 상부 적재 금지</label></div></div><button class="delete-product" data-delete="${i}" aria-label="${esc(p.name)} 삭제">×</button></div>`).join(''):'<div class="list-empty">아직 등록된 제품이 없습니다.</div>';
  document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{products.splice(+b.dataset.delete,1);renderProducts()});
  document.querySelectorAll('[data-qty-up]').forEach(button=>button.onclick=()=>changeProductQty(+button.dataset.qtyUp,1));
  document.querySelectorAll('[data-qty-down]').forEach(button=>button.onclick=()=>changeProductQty(+button.dataset.qtyDown,-1));
  document.querySelectorAll('[data-qty-input]').forEach(input=>{input.onchange=()=>setProductQty(+input.dataset.qtyInput,input.value);input.onkeydown=e=>{if(e.key==='Enter'){input.blur();e.preventDefault()}}});
  document.querySelectorAll('[data-lay]').forEach(input=>input.onchange=()=>{products[+input.dataset.lay].rotate=input.checked;markSimulationChanged()});
  document.querySelectorAll('[data-fragile]').forEach(input=>input.onchange=()=>{products[+input.dataset.fragile].fragile=input.checked;markSimulationChanged()});
  window.loadwiseStorage?.markDirty();
}

function projectSnapshot(){let resultSummary=null;if(shipment){const outcome=shipmentOutcome(shipment);resultSummary={state:outcome.state,loaded:outcome.loaded,total:outcome.total,containerCount:shipment.containers.length,totalWeight:shipment.containers.reduce((sum,load)=>sum+load.totalWeight,0),calculatedAt:new Date().toISOString()}}return LoadwiseProjectModel.createSnapshot(products,$('containerType').value,$('optimization').value,{algorithmVersion:LoadwiseProjectModel.CURRENT_ALGORITHM_VERSION,transportMode:$('transportMode').value,resultSummary,fieldResult})}
function applyProjectSnapshot(snapshot){const data=LoadwiseProjectModel.normalizeSnapshot(snapshot);products=data.products.map((p,i)=>({...p,id:Date.now()+i,color:COLORS[i%COLORS.length]}));fieldResult=data.fieldResult;$('containerType').value=data.containerType;$('optimization').value=data.optimization;$('transportMode').value=data.transportMode;result=null;shipment=null;activeContainer=0;visibleStep=0;$('balanceCard').hidden=true;$('exportPdf').disabled=true;updateContainerSpec();renderProducts();markSimulationChanged();resizeCanvas();draw()}
function resetProject(){applyProjectSnapshot({products:[],containerType:'20ft',optimization:'intelligent',transportMode:'combined'})}
if(typeof window!=='undefined')window.loadwiseProject={algorithmVersion:LoadwiseProjectModel.CURRENT_ALGORITHM_VERSION,snapshot:projectSnapshot,apply:applyProjectSnapshot,reset:resetProject};
function changeProductQty(index,delta){if(!products[index])return;products[index].qty=Math.max(1,products[index].qty+delta);renderProducts();markSimulationChanged()}
function setProductQty(index,value){if(!products[index])return;const qty=Math.max(1,Math.floor(Number(value)||1));if(products[index].qty===qty){renderProducts();return}products[index].qty=qty;renderProducts();markSimulationChanged()}
function markSimulationChanged(){$('recalculateList').classList.add('needs-update');$('recalculateList').innerHTML='다시 계산 <b>→</b>';$('recalculateOptions').classList.add('needs-update');$('recalculateOptions').innerHTML='다시 계산 <b>→</b>'}
function updateContainerSpec(){const c=CONTAINERS[$('containerType').value]||CONTAINERS['20ft'];$('containerSpec').innerHTML=`<span>내부</span><strong>${(c.l/1000).toFixed(2)} × ${(c.w/1000).toFixed(2)} × ${(c.h/1000).toFixed(2)} m</strong><i></i><span>최대</span><strong>${(c.maxWeight/1000).toFixed(1)} t</strong>`}

function transverseVoidAfterPlacement(s,d,placed,c){
  const [l,w,h]=d,x=s.x+l/2,intervals=[[s.y,s.y+w]];
  placed.forEach(p=>{if(x>p.x+1&&x<p.x+p.l-1&&s.z<p.z+p.h&&s.z+h>p.z)intervals.push([p.y,p.y+p.w])});
  intervals.sort((a,b)=>a[0]-b[0]);const merged=[];intervals.forEach(v=>{const last=merged[merged.length-1];if(last&&v[0]<=last[1]+2)last[1]=Math.max(last[1],v[1]);else merged.push([...v])});
  const covered=merged.reduce((sum,v)=>sum+v[1]-v[0],0),internal=merged.slice(1).reduce((sum,v,i)=>sum+Math.max(0,v[0]-merged[i][1]),0);
  return{internal,total:Math.max(0,c.w-covered)};
}
function preparePackingWidths(units,maxWidth=2352){const types=new Set(units.map(p=>`${p.l}x${p.w}x${p.h}:${p.rotate?1:0}`)),signature=`${maxWidth}:${[...types].sort().join('|')}`;if(signature===packingWidthSignature)return;packingWidths=[...new Set(units.flatMap(p=>allowedRotations(p).map(d=>Math.round(d[1]))).filter(w=>w>0&&w<=maxWidth))].sort((a,b)=>a-b);packingTypeCount=types.size;packingWidthSignature=signature;widthGapCache.clear()}
function projectedWidthGap(remaining){if(remaining<=0)return 0;if(packingTypeCount<=1)return remaining;const widths=packingWidths.filter(w=>w<=remaining),key=`${Math.round(remaining)}:${widths.join('-')}`;if(widthGapCache.has(key))return widthGapCache.get(key);if(!widths.length)return remaining;const reachable=new Uint8Array(Math.floor(remaining)+1);reachable[0]=1;for(let used=0;used<=remaining;used++){if(!reachable[used])continue;for(const width of widths)if(used+width<=remaining)reachable[used+width]=1}for(let used=Math.floor(remaining);used>=0;used--)if(reachable[used]){const gap=remaining-used;widthGapCache.set(key,gap);return gap}return remaining}
function cargoStabilityRisk(item){const base=Math.max(1,Math.min(item.l,item.w)),slender=item.h/base;return(item.shape==='cylinder'?2:0)+(slender>1.15?1:0)+(item.h>=1200?1:0)}
function sortUnitsForPacking(units,priority,variant=0){const tie=(a,b)=>String(a.name).localeCompare(String(b.name))||(a.unit||0)-(b.unit||0),comparators=[(a,b)=>b.volume-a.volume||(b.l*b.w-a.l*a.w)||b.weight-a.weight,(a,b)=>Math.max(b.l,b.w,b.h)-Math.max(a.l,a.w,a.h)||(b.l*b.w-a.l*a.w)||b.volume-a.volume,(a,b)=>(b.l*b.w-a.l*a.w)||b.h-a.h||b.volume-a.volume,(a,b)=>b.weight-a.weight||b.volume-a.volume];const compare=comparators[variant%comparators.length];units.sort((a,b)=>compare(a,b)||(priority==='volume'?0:cargoStabilityRisk(b)-cargoStabilityRisk(a))||tie(a,b))}
function placementCollides(s,d,placed){const [l,w,h]=d;return placed.some(p=>s.x<p.x+p.l&&s.x+l>p.x&&s.y<p.y+p.w&&s.y+w>p.y&&s.z<p.z+p.h&&s.z+h>p.z)}
function isExtremePlacement(s,d,placed){return(s.x<=0||placementCollides({...s,x:s.x-1},d,placed))&&(s.y<=0||placementCollides({...s,y:s.y-1},d,placed))&&(s.z<=0||placementCollides({...s,z:s.z-1},d,placed))}
function placementBalanceScore(item,s,d,placed,c){const total=placed.reduce((sum,p)=>sum+p.weight,0)+item.weight,cx=(placed.reduce((sum,p)=>sum+(p.x+p.l/2)*p.weight,0)+(s.x+d[0]/2)*item.weight)/total,cy=(placed.reduce((sum,p)=>sum+(p.y+p.w/2)*p.weight,0)+(s.y+d[1]/2)*item.weight)/total;return Math.abs(cx/c.l-.5)+Math.abs(cy/c.w-.5)}
function extremePoints(placed,c){const xs=new Set([0]),ys=new Set([0]),zs=new Set([0]);placed.forEach(p=>{if(p.x+p.l<c.l)xs.add(p.x+p.l);if(p.y+p.w<c.w)ys.add(p.y+p.w);if(p.z+p.h<c.h)zs.add(p.z+p.h)});const points=[];for(const z of zs)for(const x of xs)for(const y of ys)if(!placed.some(p=>x>=p.x&&x<p.x+p.l&&y>=p.y&&y<p.y+p.w&&z>=p.z&&z<p.z+p.h))points.push({x,y,z});return points.sort((a,b)=>a.z-b.z||a.x-b.x||a.y-b.y)}
function supportingItems(item,s,d,placed){if(s.z===0)return[];const [l,w]=d,cx=s.x+l/2,cy=s.y+w/2;return placed.filter(p=>{const ox=Math.min(s.x+l,p.x+p.l)-Math.max(s.x,p.x),oy=Math.min(s.y+w,p.y+p.w)-Math.max(s.y,p.y);if(Math.abs(p.z+p.h-s.z)>=2||ox<=2||oy<=2)return false;if(p.shape!=='cylinder')return true;if(item.shape!=='cylinder')return false;const centerOffset=Math.hypot(p.x+p.l/2-cx,p.y+p.w/2-cy),diameterDiff=Math.abs(p.l-l)+Math.abs(p.w-w);return centerOffset<=15&&diameterDiff<=30})}
function placementSupportRatio(item,s,d,placed){if(s.z===0)return 1;const [l,w]=d,base=l*w,support=supportingItems(item,s,d,placed).reduce((sum,p)=>{const ox=Math.max(0,Math.min(s.x+l,p.x+p.l)-Math.max(s.x,p.x)),oy=Math.max(0,Math.min(s.y+w,p.y+p.w)-Math.max(s.y,p.y));return sum+ox*oy},0);return Math.min(1,support/Math.max(1,base))}
function supportContainsCenter(item,s,d,placed){if(s.z===0)return true;const [l,w]=d,cx=s.x+l/2,cy=s.y+w/2;return supportingItems(item,s,d,placed).some(p=>{const x0=Math.max(s.x,p.x),x1=Math.min(s.x+l,p.x+p.l),y0=Math.max(s.y,p.y),y1=Math.min(s.y+w,p.y+p.w);return cx>=x0-2&&cx<=x1+2&&cy>=y0-2&&cy<=y1+2})}
function compressionLoads(placed){const carried=placed.map(p=>p.weight),top=placed.map(()=>0);[...placed.keys()].sort((a,b)=>placed[b].z-placed[a].z).forEach(i=>{const p=placed[i];if(p.z<=0)return;const supports=placed.map((q,j)=>({j,area:j===i||Math.abs(q.z+q.h-p.z)>=2?0:Math.max(0,Math.min(p.x+p.l,q.x+q.l)-Math.max(p.x,q.x))*Math.max(0,Math.min(p.y+p.w,q.y+q.w)-Math.max(p.y,q.y))})).filter(v=>v.area>0),area=supports.reduce((sum,v)=>sum+v.area,0);supports.forEach(({j,area:a})=>{const load=carried[i]*a/area;top[j]+=load;carried[j]+=load})});return top}
function compressionSafe(item,s,d,placed){if(!Number.isFinite(item.maxTopLoadKg)&&!placed.some(p=>Number.isFinite(p.maxTopLoadKg)))return true;const all=[...placed,{...item,x:s.x,y:s.y,z:s.z,l:d[0],w:d[1],h:d[2]}],loads=compressionLoads(all);return all.every((p,i)=>!Number.isFinite(p.maxTopLoadKg)||loads[i]<=p.maxTopLoadKg+1e-6)}
function lateralSupportDirections(s,d,placed,c,packing=false){const [l,w,h]=d,overlap=(a0,a1,b0,b1)=>Math.max(0,Math.min(a1,b1)-Math.max(a0,b0)),yz=p=>overlap(s.y,s.y+w,p.y,p.y+p.w)>=w*.5&&overlap(s.z,s.z+h,p.z,p.z+p.h)>=h*.5,xz=p=>overlap(s.x,s.x+l,p.x,p.x+p.l)>=l*.5&&overlap(s.z,s.z+h,p.z,p.z+p.h)>=h*.5,low=placed.some(p=>Math.abs(p.x+p.l-s.x)<=2&&yz(p)),high=placed.some(p=>Math.abs(s.x+l-p.x)<=2&&yz(p));return{front:packing?high:low,back:(packing?s.x<=2:s.x+l>=c.l-2)||(packing?low:high),left:s.y<=2||placed.some(p=>Math.abs(p.y+p.w-s.y)<=2&&xz(p)),right:s.y+w>=c.w-2||placed.some(p=>Math.abs(s.y+w-p.y)<=2&&xz(p))}}
function transportPlacementRisk(item,s,d,placed,c,mode=currentTransportMode()){const profile=TRANSPORT_PROFILES[mode]||TRANSPORT_PROFILES.combined,sides=lateralSupportDirections(s,d,placed,c,true),supported=Object.values(sides).filter(Boolean).length,base=Math.max(1,Math.min(d[0],d[1])),slender=d[2]/base,column=(s.z+d[2])/base;let risk=Math.max(0,slender-profile.slender)*(4-supported)+Math.max(0,column-profile.column)*(4-supported);if(s.z>0&&!sides.left&&!sides.right)risk+=2;if(mode==='sea'&&s.z>0&&s.x+d[0]>=c.l-120&&!sides.front)risk+=1;if(item.shape==='cylinder'&&(!sides.left||!sides.right))risk+=1;return risk}
function validSupport(item,s,d,placed,priority,c){const columnSlender=(s.z+d[2])/Math.max(1,Math.min(d[0],d[1]));if(columnSlender>1.5&&Object.values(lateralSupportDirections(s,d,placed,c,true)).filter(Boolean).length<2)return false;if(s.z===0)return true;const ratio=placementSupportRatio(item,s,d,placed),supports=supportingItems(item,s,d,placed);if(ratio<(priority==='volume'?.7:1)-1e-6||!supports.length||supports.some(p=>p.fragile)||!supportContainsCenter(item,s,d,placed))return false;if(priority==='volume')return true;const slender=d[2]/Math.max(1,Math.min(d[0],d[1]));return slender<=1.15}
function findExtremePlacement(c,item,placed,priority,floorOnly=false){let best=null;const usedDepth=placed.reduce((m,p)=>Math.max(m,p.x+p.l),0);for(const s of extremePoints(placed,c)){if(floorOnly&&s.z>0)break;let pointBest=null;for(const d of allowedRotations(item)){if(s.x+d[0]>c.l||s.y+d[1]>c.w||s.z+d[2]>c.h||placementCollides(s,d,placed)||!isExtremePlacement(s,d,placed)||!validSupport(item,s,d,placed,priority,c)||!compressionSafe(item,s,d,placed))continue;const gap=transverseVoidAfterPlacement(s,d,placed,c),support=placementSupportRatio(item,s,d,placed),risk=transportPlacementRisk(item,s,d,placed,c),riskScore=(risk>0?1e20:0)+risk*1e18,rotationScore=riskScore+gap.internal*1e12+projectedWidthGap(gap.total)*1e8+(1-support)*1e6-d[0]*d[1];if(!pointBest||rotationScore<pointBest.score)pointBest={d,score:rotationScore};if(priority==='volume'){const newDepth=Math.max(usedDepth,s.x+d[0]),score=newDepth*1e15+gap.internal*1e12+s.z*1e9+projectedWidthGap(gap.total)*1e6+rotationScore;if(!best||score<best.score)best={s,d,score}}else if(priority==='width'||priority==='hybrid'){const newDepth=Math.max(usedDepth,s.x+d[0]),unsupported=priority==='hybrid'?4-Object.values(lateralSupportDirections(s,d,placed,c,true)).filter(Boolean).length:0,score=riskScore+projectedWidthGap(gap.total)*1e15+gap.internal*1e12+unsupported*1e10+gap.total*1e8+s.z*1e5+newDepth;if(!best||score<best.score)best={s,d,score}}else if(priority==='balance'){const newDepth=Math.max(usedDepth,s.x+d[0]),score=newDepth*1e15+gap.internal*1e12+s.z*1e9+placementBalanceScore(item,s,d,placed,c)*1e8+rotationScore;if(!best||score<best.score)best={s,d,score}}}if(priority==='sequence'&&pointBest)return{s,d:pointBest.d}}return best}
function placeExtremeItem(item,best,placed){const [l,w,h]=best.d;placed.push({...item,x:best.s.x,y:best.s.y,z:best.s.z,l,w,h})}
function packExtremeRaw(c,source,priority,seed=[],initialWeight=0,orderVariant=0){const units=[...source];sortUnitsForPacking(units,priority,orderVariant);const placed=seed.map(p=>({...p})),rejected=[];let totalWeight=initialWeight,pending=units;if(priority==='sequence'||priority==='hybrid')while(pending.length){let added=false;const deferred=[];for(const item of pending){if(totalWeight+item.weight>c.maxWeight){deferred.push(item);continue}const best=findExtremePlacement(c,item,placed,priority,true);if(!best){deferred.push(item);continue}placeExtremeItem(item,best,placed);totalWeight+=item.weight;added=true}pending=deferred;if(!added)break}for(const item of pending){if(totalWeight+item.weight>c.maxWeight){rejected.push({...item,reason:'중량 초과'});continue}const best=findExtremePlacement(c,item,placed,priority,false);if(!best){rejected.push({...item,reason:'공간 또는 지지 조건 부족'});continue}placeExtremeItem(item,best,placed);totalWeight+=item.weight}return{placed,rejected,totalWeight}}
async function packExtremeRawAsync(c,source,priority,seed=[],initialWeight=0,onProgress=()=>{},orderVariant=0){const units=[...source];sortUnitsForPacking(units,priority,orderVariant);const placed=seed.map(p=>({...p})),rejected=[];let totalWeight=initialWeight,pending=units,operations=0,totalOps=Math.max(1,units.length*2),tick=async()=>{operations++;onProgress(Math.min(.98,operations/totalOps));if(operations%2===0)await new Promise(resolve=>setTimeout(resolve,0))};if(priority==='sequence'||priority==='hybrid')while(pending.length){let added=false;const deferred=[];for(const item of pending){if(totalWeight+item.weight>c.maxWeight){deferred.push(item);await tick();continue}const best=findExtremePlacement(c,item,placed,priority,true);if(!best)deferred.push(item);else{placeExtremeItem(item,best,placed);totalWeight+=item.weight;added=true}await tick()}pending=deferred;if(!added)break}for(const item of pending){if(totalWeight+item.weight>c.maxWeight)rejected.push({...item,reason:'중량 초과'});else{const best=findExtremePlacement(c,item,placed,priority,false);if(!best)rejected.push({...item,reason:'공간 또는 지지 조건 부족'});else{placeExtremeItem(item,best,placed);totalWeight+=item.weight}}await tick()}onProgress(1);return{placed,rejected,totalWeight}}
function centerCargoByWeight(placed,c){if(!placed.length)return;const total=placed.reduce((sum,p)=>sum+p.weight,0),cog=axis=>placed.reduce((sum,p)=>sum+(p[axis]+p[axis==='x'?'l':'w']/2)*p.weight,0)/total,shift=(axis,size,target)=>{const min=Math.min(...placed.map(p=>p[axis])),max=Math.max(...placed.map(p=>p[axis]+p[size])),wanted=Math.round(target-cog(axis)),delta=Math.max(-min,Math.min(wanted,c[axis==='x'?'l':'w']-max));placed.forEach(p=>p[axis]+=delta)};shift('x','l',c.l/2);shift('y','w',c.w/2)}
function finalizePacking(c,raw){const placed=raw.placed.map(p=>({...p}));if(raw.priority==='balance')centerCargoByWeight(placed,c);else shiftCargoInside(placed,c);orderPlacementsForLoading(placed);const volume=placed.reduce((sum,p)=>sum+p.l*p.w*p.h,0);return{container:c,placed,rejected:raw.rejected,totalWeight:raw.totalWeight,volumeRate:volume/(c.l*c.w*c.h)*100,weightRate:raw.totalWeight/c.maxWeight*100}}
function packingDepth(raw){return raw.placed.reduce((m,p)=>Math.max(m,p.x+p.l),0)}
function rawBalanceRisk(raw,c){const weight=raw.placed.reduce((sum,p)=>sum+p.weight,0);if(!weight)return Infinity;const x=raw.placed.reduce((sum,p)=>sum+(p.x+p.l/2)*p.weight,0)/weight,y=raw.placed.reduce((sum,p)=>sum+(p.y+p.w/2)*p.weight,0)/weight;return Math.abs(x/c.l-.5)+Math.abs(y/c.w-.5)}
function chooseRaw(c,priority,plans){const chosen=[...plans].sort((a,b)=>b.placed.length-a.placed.length||(priority==='balance'?rawBalanceRisk(a,c)-rawBalanceRisk(b,c):0)||packingDepth(a)-packingDepth(b))[0];return{...chosen,priority}}
function orderVariants(units,force=false){const types=new Set(units.map(p=>`${p.l}x${p.w}x${p.h}:${p.weight}`)).size;return(force||types>1)&&units.length<=80?[0,1,2]:[0]}
function packPlan(c,units,priority){preparePackingWidths(units);if(priority==='width'||priority==='hybrid'||priority==='balance'||priority==='sequence'){const first=packExtremeRaw(c,units,priority),variants=orderVariants(units,priority==='balance'||priority==='hybrid'||first.rejected.length>0),plans=[first,...variants.slice(1).map(v=>packExtremeRaw(c,units,priority,[],0,v))];if(priority!=='sequence'&&plans.every(p=>p.rejected.length))plans.push(packExtremeRaw(c,units,'sequence'),packExtremeRaw(c,units,'volume'));return finalizePacking(c,chooseRaw(c,priority,plans))}const safe=packExtremeRaw(c,units,'sequence'),expanded=packExtremeRaw(c,safe.rejected,'volume',safe.placed,safe.totalWeight),dense=packExtremeRaw(c,units,'volume'),best=chooseRaw(c,priority,[safe,expanded,dense]);return finalizePacking(c,best)}
async function packPlanAsync(c,units,priority,onProgress=()=>{},refine=true){preparePackingWidths(units);if(priority==='width'||priority==='hybrid'||priority==='balance'||priority==='sequence'){const first=await packExtremeRawAsync(c,units,priority,[],0,p=>onProgress(p*(refine?.5:1))),variants=refine?orderVariants(units,priority==='balance'||priority==='hybrid'||first.rejected.length>0):[0],plans=[first];for(const [i,v]of variants.slice(1).entries())plans.push(await packExtremeRawAsync(c,units,priority,[],0,p=>onProgress(.5+(i+p)*( .5/Math.max(1,variants.length-1))),v));if(priority!=='sequence'&&plans.every(p=>p.rejected.length))plans.push(await packExtremeRawAsync(c,units,'sequence',[],0,()=>{}),await packExtremeRawAsync(c,units,'volume',[],0,()=>{}));onProgress(1);return finalizePacking(c,chooseRaw(c,priority,plans))}const safe=await packExtremeRawAsync(c,units,'sequence',[],0,p=>onProgress(p*.35)),expanded=await packExtremeRawAsync(c,safe.rejected,'volume',safe.placed,safe.totalWeight,p=>onProgress(.35+p*.25)),dense=await packExtremeRawAsync(c,units,'volume',[],0,p=>onProgress(.6+p*.35)),best=chooseRaw(c,priority,[safe,expanded,dense]);onProgress(1);return finalizePacking(c,best)}
async function packShipmentAsync(c,units,priority,onProgress=()=>{},refine=true){const loads=[];let remaining=units;while(remaining.length&&loads.length<50){const load=await packPlanAsync(c,remaining,priority,p=>onProgress((loads.length+Math.min(1,p))/(loads.length+1)),refine);if(!load.placed.length){if(!loads.length)loads.push(load);break}loads.push(load);remaining=load.rejected}return{priority,loads,remaining}}
function strategyScore(plan,transportMode=currentTransportMode()){const loaded=plan.loads.reduce((sum,load)=>sum+load.placed.length,0),insights=plan.loads.map(load=>LoadwiseInsights.ctu?.(load)||LoadwiseInsights.balance(load)),ctuLevel=insights.reduce((worst,value)=>Math.max(worst,value?.level==='danger'?2:value?.level==='caution'?1:0),0),ctuExcess=insights.reduce((worst,value)=>Math.max(worst,value?Math.max(0,(value.concentration||0)-60,(value.vertical||0)-50):100),0),balance=insights.reduce((worst,value)=>Math.max(worst,value?Math.max(Math.abs(value.xOffset),Math.abs(value.yOffset)):100),0),review=plan.loads.reduce((sum,load)=>sum+buildSecuringPlan(load,transportMode).reviews.length,0),depth=plan.loads.reduce((sum,load)=>sum+packingDepth(load),0);return[plan.remaining.length,plan.loads.length,ctuLevel,review,ctuExcess,balance,-loaded,depth]}
function selectBestStrategy(plans,transportMode=currentTransportMode()){const best=[...plans].sort((a,b)=>{const A=strategyScore(a,transportMode),B=strategyScore(b,transportMode);for(let i=0;i<A.length;i++)if(A[i]!==B[i])return A[i]-B[i];return Object.keys(STRATEGIES).indexOf(a.priority)-Object.keys(STRATEGIES).indexOf(b.priority)})[0],score=strategyScore(best,transportMode),ctu=score[2]===0?'안정':score[2]===1?'주의':'위험';return{...best,label:STRATEGIES[best.priority].label,reason:`${Object.keys(STRATEGIES).length}개 전략 비교 · 미배치 ${score[0]}개 · 컨테이너 ${score[1]}대 · CTU 사전검사 ${ctu} · 운송 안정성 검토 ${score[3]}건 · 최대 중심편차 ${score[5].toFixed(1)}%`}}
function updateSimulationProgress(status,progress,label='배치 후보 계산 중'){const percent=Math.max(0,Math.min(100,Math.round(progress)));status.innerHTML=`<i></i><span>${label}</span><b>${percent}%</b><em><u style="width:${percent}%"></u></em>`}
function shipmentOutcome(s){const loaded=s.containers.reduce((sum,load)=>sum+load.placed.length,0),left=s.unallocated.length,total=s.totalUnits,rate=total?Math.round(loaded/total*100):0;return{loaded,left,total,rate,state:left===0?'complete':loaded===0?'failed':'partial'}}
function unallocatedNotice(s){const outcome=shipmentOutcome(s),groups=new Map;s.unallocated.forEach(item=>{const key=`${item.name}\0${item.reason||''}`,group=groups.get(key)||{name:item.name,reason:item.reason||'치수·회전·지지 조건 불충족',count:0};group.count++;groups.set(key,group)});const details=[...groups.values()].slice(0,8).map(group=>`${group.name} × ${group.count} — ${group.reason}`).join('\n'),extra=groups.size>8?`\n외 ${groups.size-8}개 제품군`:'';return`전체 ${outcome.total}개 중 ${outcome.loaded}개만 적재되었습니다.\n\n미배치 화물 ${outcome.left}개\n${details}${extra}\n\n컨테이너 규격이나 제품의 치수·중량·회전 조건을 확인해 주세요. 미배치 화물이 있으면 Excel 내보내기가 제한됩니다.`}

async function simulate(){
  if(!products.length){showAppMessage('직접 입력하거나 파일을 불러와 제품을 하나 이상 등록한 뒤 실행해 주세요.',{title:'등록된 제품이 없습니다',tone:'warning'});return}
  if(simulationRunning)return;simulationRunning=true;const started=performance.now(),status=$('simulationStatus'),buttons=[$('recalculateList'),$('recalculateOptions')];buttons.forEach(b=>b.disabled=true);status.hidden=false;status.className='simulation-status busy';updateSimulationProgress(status,1,'계산 준비 중');await new Promise(resolve=>requestAnimationFrame(()=>setTimeout(resolve,30)));
  try{const c=CONTAINERS[$('containerType').value],requested=$('optimization').value,units=products.flatMap((p,pi)=>Array.from({length:p.qty},(_,n)=>({...p,pi,unit:n+1,volume:p.l*p.w*p.h})));let strategy;if(requested==='intelligent'){const plans=[],entries=Object.keys(STRATEGIES),span=84/entries.length;for(const [i,priority] of entries.entries()){const label=`${i+1}/${entries.length} ${STRATEGIES[priority].label} 비교 중`;updateSimulationProgress(status,5+i*span,label);plans.push(await packShipmentAsync(c,units,priority,p=>updateSimulationProgress(status,5+i*span+p*(span-2),label),false))}strategy=selectBestStrategy(plans)}else{const plan=await packShipmentAsync(c,units,requested,p=>updateSimulationProgress(status,5+p*80,`${STRATEGIES[requested].label} 계산 중`));strategy={...plan,label:STRATEGIES[requested].label,reason:'사용자 선택'}}const priority=strategy.priority,loads=strategy.loads,remaining=strategy.remaining;updateSimulationProgress(status,97,'고정재 위치 계산 중');await new Promise(resolve=>setTimeout(resolve,0));loads.forEach((load,i)=>{load.containerNumber=i+1;load.securing=buildSecuringPlan(load)});shipment={containers:loads,unallocated:remaining,totalUnits:units.length,containerKey:$('containerType').value,priority,requested,strategy:{priority,label:strategy.label,reason:strategy.reason}};shipment.validation=LoadwiseValidator.validateShipment(shipment);if(!shipment.validation.valid)throw new Error(`독립 안전 검증 실패: ${shipment.validation.errors.slice(0,3).join(' / ')}`);result=loads[0];activeContainer=0;visibleStep=result.placed.length;stopPlayback();$('recalculateList').classList.remove('needs-update');$('recalculateList').innerHTML='시뮬레이션 실행 <b>→</b>';$('recalculateOptions').classList.remove('needs-update');$('recalculateOptions').innerHTML='시뮬레이션 실행 <b>→</b>';updateResults();resizeCanvas();draw();const outcome=shipmentOutcome(shipment),elapsed=((performance.now()-started)/1000).toFixed(2),strategyText=requested==='intelligent'?` · 자동 추천 → ${strategy.label}`:` · ${strategy.label}`;status.className=`simulation-status ${outcome.state==='complete'?'done':outcome.state==='partial'?'warning':'error'}`;status.innerHTML=`<i></i><span>${outcome.state==='complete'?'적재 완료':outcome.state==='partial'?'부분 적재':'적재 불가'}${strategyText} · ${elapsed}초</span><b>적재 ${outcome.rate}%</b>`;if(outcome.left)showAppMessage(unallocatedNotice(shipment),{title:outcome.state==='failed'?'현재 조건으로 적재할 수 없습니다':'일부 화물을 적재할 수 없습니다',tone:outcome.state==='failed'?'error':'warning'});window.dispatchEvent(new CustomEvent('loadwise:simulation-complete'))}catch(error){console.error(error);status.className='simulation-status error';status.innerHTML='<i></i><span>계산 중 오류가 발생했습니다</span>';showAppMessage(error.message?.startsWith('독립 안전 검증 실패')?'계산 결과가 독립 안전 검증을 통과하지 못해 표시하지 않았습니다. 다른 최적화 기준을 선택해 다시 실행해 주세요.':'계산을 완료하지 못했습니다. 입력 조건을 확인한 뒤 다시 실행해 주세요.',{title:'시뮬레이션 오류',tone:'error'})}finally{simulationRunning=false;buttons.forEach(b=>b.disabled=!products.length)}
}
function packAdditional(c,units,priority){
  return packPlan(c,units,priority);
}
function shiftCargoInside(placed,c){if(!placed.length)return;placed.forEach(p=>p.x=c.l-(p.x+p.l))}
function orderPlacementsForLoading(placed){const remaining=[...placed],ordered=[],done=new Set(),overlap=(a0,a1,b0,b1)=>Math.min(a1,b1)-Math.max(a0,b0)>2;while(remaining.length){let eligible=remaining.filter(p=>p.z===0||placed.filter(q=>q!==p&&Math.abs(q.z+q.h-p.z)<2&&overlap(p.x,p.x+p.l,q.x,q.x+q.l)&&overlap(p.y,p.y+p.w,q.y,q.y+q.w)).every(q=>done.has(q)));if(!eligible.length)eligible=remaining;eligible.sort((a,b)=>b.x-a.x||a.z-b.z||a.y-b.y);const next=eligible[0];ordered.push(next);done.add(next);remaining.splice(remaining.indexOf(next),1)}placed.splice(0,placed.length,...ordered);placed.forEach((p,i)=>p.order=i+1)}
function transportStabilityAssessment(p,placed,c,mode=currentTransportMode()){const profile=TRANSPORT_PROFILES[mode]||TRANSPORT_PROFILES.combined,base=Math.max(1,Math.min(p.l,p.w)),itemSlender=p.h/base,columnSlender=(p.z+p.h)/base,lateral=lateralSupportDirections(p,[p.l,p.w,p.h],placed.filter(q=>q!==p),c),supported=Object.values(lateral).filter(Boolean).length,missing=Object.entries(lateral).filter(([,ok])=>!ok).map(([direction])=>({front:'전',back:'후',left:'좌',right:'우'}[direction])),reasons=[];if(itemSlender>profile.slender&&supported<profile.minSides)reasons.push(`높이 비율 ${itemSlender.toFixed(1)} · 측면 지지 ${supported}/4`);if(p.z>0&&columnSlender>profile.column&&supported<profile.minSides)reasons.push(`상단 ${((p.z+p.h)/1000).toFixed(1)}m 고단 적재`);if(p.z>0&&!lateral.left&&!lateral.right)reasons.push('상단 좌우 지지 없음');if(mode==='sea'&&p.z>0&&p.x<120&&!lateral.front)reasons.push('문측 상단 노출');if(p.shape==='cylinder'&&(!lateral.left||!lateral.right))reasons.push('원통 구름 방향 차단 확인');return reasons.length?{product:p.name,axes:missing.join('·'),severity:reasons.length>1||missing.length>=3?'rearrange':'review',location:reasons.join(' · ')}:null}
function buildSecuringPlan(load,transportMode=currentTransportMode()){
  const dunnage=[],airbags=[],reviews=[],floorItems=load.placed.filter(p=>p.z===0),c=load.container;
  const doorGap=floorItems.length?Math.min(...floorItems.map(p=>p.x)):0;
  if(floorItems.length&&doorGap>=60){
    const overlap=(a0,a1,b0,b1)=>Math.min(a1,b1)-Math.max(a0,b0)>40,front=floorItems.filter(p=>!floorItems.some(q=>q!==p&&q.x+q.l<=p.x+2&&overlap(p.y,p.y+p.w,q.y,q.y+q.w)));
    const y0=Math.max(0,Math.min(...front.map(p=>p.y))),y1=Math.min(c.w,Math.max(...front.map(p=>p.y+p.w))),span=Math.max(300,y1-y0),beamL=Math.min(100,Math.max(65,doorGap-18)),beamX=Math.max(0,doorGap-beamL-8);
    dunnage.push({type:'dunnage',kind:'beam',axis:'x',side:'min',x:beamX,y:y0,z:0,l:beamL,w:span,h:95,product:'문쪽 노출 화물 전체',location:'문쪽 전면 가로 각재'});
    const count=Math.max(3,Math.min(6,Math.ceil(span/420))),chockL=Math.min(180,Math.max(75,beamX-8));
    for(let i=0;i<count;i++){const center=y0+span*(i+.5)/count,w=Math.min(150,span/count*.55);dunnage.push({type:'dunnage',kind:'chock',axis:'x',side:'min',x:Math.max(0,beamX-chockL-5),y:Math.max(0,Math.min(c.w-w,center-w/2)),z:0,l:chockL,w,h:125,product:'문쪽 노출 화물 전체',location:`가로 각재 지지 부목 ${i+1}/${count}`})}
  }
  {
    const candidates=[];
    load.placed.forEach(p=>{const left=p.y,right=c.w-(p.y+p.w),back=c.l-(p.x+p.l),length=Math.min(700,p.l*.6),width=Math.min(700,p.w*.6),x=p.x+(p.l-length)/2,y=p.y+(p.w-width)/2,height=Math.min(1200,p.h*.72),z=p.z+Math.max(20,p.h*.14),level=p.z>0?`${Math.round(p.z/1000*10)/10}m 높이`:'',addWall=(zone,gap,make)=>{if(gap<100)return;const count=Math.ceil(gap/600),size=gap/count;for(let i=0;i<count;i++)candidates.push({...make(i,size),type:'airbag',zone,z,h:height,location:`${zone==='left'?'좌측':zone==='right'?'우측':'안쪽'} 벽 간극 ${Math.round(gap)}mm${count>1?` · 분할 ${i+1}/${count}`:''} ${level}`.trim(),product:p.name})};addWall('left',left,(i,size)=>({x,y:i*size,l:length,w:size}));addWall('right',right,(i,size)=>({x,y:p.y+p.w+i*size,l:length,w:size}));addWall('back',back,(i,size)=>({x:p.x+p.l+i*size,y,l:size,w:width}))});
    const sorted=[...load.placed].sort((a,b)=>a.x-b.x);sorted.forEach((p,i)=>{let nearest=null;for(let j=i+1;j<sorted.length;j++){const q=sorted[j],gap=q.x-(p.x+p.l),overlap=Math.min(p.y+p.w,q.y+q.w)-Math.max(p.y,q.y),vertical=Math.min(p.z+p.h,q.z+q.h)-Math.max(p.z,q.z);if(gap>0&&overlap>150&&vertical>150&&(!nearest||gap<nearest.gap))nearest={q,gap,overlap,vertical}}if(nearest&&nearest.gap>=120&&nearest.gap<=600){const baseZ=Math.max(p.z,nearest.q.z),z=baseZ+Math.max(20,nearest.vertical*.14);candidates.push({type:'airbag',zone:'cargo',x:p.x+p.l,y:Math.max(p.y,nearest.q.y),z,l:nearest.gap,w:nearest.overlap,h:Math.min(1200,nearest.vertical*.72),location:`화물 사이 간극${baseZ>0?` · ${(baseZ/1000).toFixed(1)}m 높이`:''}`,product:`${p.name} / ${nearest.q.name}`})}});
    const byY=[...load.placed].sort((a,b)=>a.y-b.y);byY.forEach((p,i)=>{let nearest=null;for(let j=i+1;j<byY.length;j++){const q=byY[j],gap=q.y-(p.y+p.w),overlap=Math.min(p.x+p.l,q.x+q.l)-Math.max(p.x,q.x),vertical=Math.min(p.z+p.h,q.z+q.h)-Math.max(p.z,q.z);if(gap>0&&overlap>180&&vertical>150&&(!nearest||gap<nearest.gap))nearest={q,gap,overlap,vertical}}if(nearest&&nearest.gap>=120&&nearest.gap<=600){const baseZ=Math.max(p.z,nearest.q.z),z=baseZ+Math.max(20,nearest.vertical*.12);candidates.push({type:'airbag',zone:'center',x:Math.max(p.x,nearest.q.x),y:p.y+p.w,z,l:nearest.overlap,w:nearest.gap,h:Math.min(1400,nearest.vertical*.76),location:`화물 열 사이 중앙 간극${baseZ>0?` · ${(baseZ/1000).toFixed(1)}m 높이`:''}`,product:`${p.name} / ${nearest.q.name}`})}});
    const free=q=>!load.placed.some(p=>q.x<p.x+p.l&&q.x+q.l>p.x&&q.y<p.y+p.w&&q.y+q.w>p.y&&q.z<p.z+p.h&&q.z+q.h>p.z);
    const overlapRatio=(a0,a1,b0,b1)=>Math.max(0,Math.min(a1,b1)-Math.max(a0,b0))/Math.max(1,Math.min(a1-a0,b1-b0));
    const grounded=candidates.map(q=>({...q,h:q.z+q.h,z:0,location:`${q.location.replace(/\s*·?\s*\d+(?:\.\d+)?m 높이/g,'')} · 바닥 설치`}));
    grounded.filter(free).sort((a,b)=>(b.l*b.w*b.h-a.l*a.w*a.h)).forEach(q=>{const duplicate=airbags.some(a=>overlapRatio(a.x,a.x+a.l,q.x,q.x+q.l)>.55&&overlapRatio(a.y,a.y+a.w,q.y,q.y+q.w)>.55&&overlapRatio(a.z,a.z+a.h,q.z,q.z+q.h)>.35);if(!duplicate)airbags.push(q)});
    const zoneName={left:'좌측 벽 간극',right:'우측 벽 간극',back:'안쪽 벽 간극',door:'문쪽 간극',center:'화물 열 사이 중앙 간극'};
    let combined=true;
    while(combined){combined=false;outer:for(let i=0;i<airbags.length;i++)for(let j=i+1;j<airbags.length;j++){const a=airbags[i],b=airbags[j];if(!a.zone||a.zone==='cargo'||a.zone!==b.zone)continue;const horizontal=overlapRatio(a.x,a.x+a.l,b.x,b.x+b.l)>.55&&overlapRatio(a.y,a.y+a.w,b.y,b.y+b.w)>.55,verticalGap=Math.max(0,Math.max(a.z,b.z)-Math.min(a.z+a.h,b.z+b.h));if(!horizontal||verticalGap>350)continue;const x=Math.max(a.x,b.x),y=Math.max(a.y,b.y),z=Math.min(a.z,b.z),l=Math.min(a.x+a.l,b.x+b.l)-x,w=Math.min(a.y+a.w,b.y+b.w)-y,h=Math.max(a.z+a.h,b.z+b.h)-z,merged={type:'airbag',zone:a.zone,x,y,z,l,w,h,location:`${zoneName[a.zone]} · 대형 수직 통합`,product:`${a.product} / ${b.product}`,combined:(a.combined||1)+(b.combined||1)};if(l>100&&w>100&&h<=c.h-z&&free(merged)){airbags.splice(j,1);airbags.splice(i,1,merged);combined=true;break outer}}}
    airbags.sort((a,b)=>(b.combined||1)-(a.combined||1)||b.z-a.z);if(airbags.length>14)airbags.splice(14);
  }
  load.placed.forEach(p=>{const review=transportStabilityAssessment(p,load.placed,c,transportMode);if(review){const same=reviews.find(item=>item.product===review.product&&item.location===review.location&&item.axes===review.axes&&item.severity===review.severity);if(same)same.count++;else reviews.push({...review,count:1})}});
  return{dunnage,airbags,reviews,transportMode};
}
function uniqueRotations(p){const a=[[p.l,p.w,p.h],[p.w,p.l,p.h],[p.l,p.h,p.w],[p.h,p.l,p.w],[p.w,p.h,p.l],[p.h,p.w,p.l]];return a.filter((x,i)=>a.findIndex(y=>y.join()==x.join())===i)}
function allowedRotations(p){return p.rotate?uniqueRotations(p):uniqueRotations({l:p.l,w:p.w,h:p.h}).filter(d=>d[2]===p.h)}
function updateResults(){
  const r=result,total=shipment?shipment.totalUnits:products.reduce((s,p)=>s+p.qty,0);$('emptyState').style.display='none';$('canvasHint').style.display='block';document.querySelector('.axis-legend').style.display='flex';renderContainerTabs();
  $('volumeRate').textContent=`${r.volumeRate.toFixed(1)}%`;$('weightRate').textContent=`${r.weightRate.toFixed(1)}%`;$('volumeBar').style.width=`${Math.min(100,r.volumeRate)}%`;$('weightBar').style.width=`${Math.min(100,r.weightRate)}%`;
  $('loadedCount').textContent=`${r.placed.length}개`;$('loadedDetail').textContent=`컨테이너 ${r.containerNumber||1} · 전체 ${total}개`;$('totalWeight').textContent=`${r.totalWeight.toLocaleString()} kg`;$('weightDetail').textContent=`허용 ${(r.container.maxWeight/1000).toFixed(1)} t`;
  const groups=[];r.placed.forEach(p=>{let g=groups.find(x=>x.name===p.name&&x.z===p.z&&x.x===p.x);if(g)g.count++;else groups.push({...p,count:1})});
  $('sequenceEmpty').style.display=r.placed.length?'none':'block';$('sequenceEmpty').textContent=r.placed.length?'':'적재 가능한 화물이 없습니다.';$('sequenceList').innerHTML=groups.map((p,i)=>`<li><span class="num">${String(i+1).padStart(2,'0')}</span><span class="dot" style="background:${p.color};border-radius:${p.shape==='cylinder'?'50%':'2px'}"></span><div><strong>${esc(p.name)} × ${p.count} · ${p.shape==='cylinder'?'원통형':'박스형'}</strong><br><small>문에서 ${(p.x/1000).toFixed(2)}m 안쪽 · 바닥에서 ${(p.z/1000).toFixed(2)}m 높이</small></div><small>${p.l}×${p.w}×${p.h}</small></li>`).join('');const blocked=shipment?.unallocated.length>0;$('exportPlan').disabled=blocked;$('exportPlan').title=blocked?`미배치 화물 ${shipment.unallocated.length}개를 해결한 후 내보낼 수 있습니다.`:'';
  $('playback').style.display='flex';$('stepRange').max=r.placed.length;$('totalSteps').textContent=r.placed.length;$('exportPdf').disabled=blocked;$('exportPdf').title=blocked?`미배치 화물 ${shipment.unallocated.length}개를 해결한 후 만들 수 있습니다.`:'';setStep(r.placed.length);renderBalance();renderRecommendation();renderSecuringRecommendation();requestAnimationFrame(syncSequenceHeight);
}
function renderBalance(){const value=LoadwiseInsights.ctu(result),card=$('balanceCard');if(!value){card.hidden=true;return}const validation=LoadwiseValidator.validateLoad(result,{minSupport:shipment?.priority==='volume'?.7:1}),m=validation.metrics;card.hidden=false;card.dataset.level=value.level;$('balanceStatus').textContent=value.level==='safe'?'안정':value.level==='caution'?'주의':'위험';$('frontRearBalance').textContent=`${value.door.toFixed(1)}% / ${value.rear.toFixed(1)}%`;$('leftRightBalance').textContent=`${value.left.toFixed(1)}% / ${value.right.toFixed(1)}%`;$('cogPosition').textContent=`X ${(value.cog.x/1000).toFixed(2)} · Y ${(value.cog.y/1000).toFixed(2)} · Z ${(value.cog.z/1000).toFixed(2)} m`;$('cogOffset').textContent=`전후 ${Math.abs(value.xOffset).toFixed(1)}% · 좌우 ${Math.abs(value.yOffset).toFixed(1)}%`;$('ctuConcentration').textContent=`${value.concentration.toFixed(1)}% · ${value.checks.concentration?'권고 이내':'60% 초과'}`;$('ctuVertical').textContent=`높이의 ${value.vertical.toFixed(1)}% · ${value.checks.vertical?'권고 이내':'50% 초과'}`;$('compressionStatus').textContent=m.compressionUnverified?`${m.compressionVerified}개 검증 · ${m.compressionUnverified}개 미입력`:`${m.compressionVerified}개 검증 완료`}
function toggleProductList(){const card=document.querySelector('.product-list-card'),expanded=card.classList.toggle('expanded'),button=$('toggleProducts');button.textContent=expanded?'접기 ▴':'펼치기 ▾';button.setAttribute('aria-expanded',expanded)}
function toggleSequence(){const plan=document.querySelector('.loading-plan'),expanded=plan.classList.toggle('expanded'),button=$('toggleSequence');button.textContent=expanded?'접기 ▴':'펼치기 ▾';button.setAttribute('aria-expanded',expanded);if(!expanded)requestAnimationFrame(syncSequenceHeight)}
function syncSequenceHeight(){const plan=document.querySelector('.loading-plan'),list=$('sequenceList'),panel=document.querySelector('.control-panel');if(!plan||!list||!panel||plan.classList.contains('expanded'))return;const available=Math.max(220,Math.round(panel.getBoundingClientRect().bottom-list.getBoundingClientRect().top-24));list.style.setProperty('--sequence-max-height',`${available}px`)}
function renderContainerTabs(){const el=$('containerTabs');if(!shipment){el.style.display='none';return}const total=shipment.containers.length;el.style.display='flex';el.innerHTML=`<button class="nav-arrow" id="prevContainer" ${activeContainer===0?'disabled':''} aria-label="이전 컨테이너">‹</button><span class="page-label">${activeContainer+1} / ${total}</span><button class="nav-arrow" id="nextContainerArrow" ${activeContainer===total-1?'disabled':''} aria-label="다음 컨테이너">›</button>`;$('prevContainer').onclick=()=>selectContainer(activeContainer-1);$('nextContainerArrow').onclick=()=>selectContainer(activeContainer+1)}
function selectContainer(index){if(!shipment||!shipment.containers[index])return;activeContainer=index;result=shipment.containers[index];visibleStep=result.placed.length;stopPlayback();updateResults();resizeCanvas();draw()}
function containerPlanMessage(container,count){return count===1?`${container.name} 1대에 한 번에 적재합니다.`:`${container.name} ${count}대로 분할 적재합니다.`}
function renderRecommendation(){
  const el=$('recommendation');if(!shipment){el.hidden=true;el.innerHTML='';return}const automatic=shipment.requested==='intelligent';if(!automatic&&shipment.containers.length===1&&!shipment.unallocated.length){el.hidden=true;el.innerHTML='';return}el.hidden=false;const c=result.container,count=shipment.containers.length,left=shipment.unallocated.length;
  const outcome=shipmentOutcome(shipment);if(outcome.state==='failed'){el.innerHTML=`<div><strong>현재 규격으로 적재할 수 없습니다.</strong><p>미배치 화물 ${left}개의 치수·중량·회전 조건을 확인하세요. 분할 대수는 제안하지 않습니다.</p></div>`;return}el.innerHTML=`<div><strong>${outcome.state==='partial'?`${c.name} ${count}대에 ${outcome.loaded}개 적재 · ${left}개 미배치`:containerPlanMessage(c,count)}</strong><p>3D 화면에서 각 컨테이너의 배치와 순서를 확인하세요.${left?' 미배치 화물은 별도 검토가 필요합니다.':''}</p></div>`;
  if(automatic)el.innerHTML=`<div><strong>자동 추천 → ${shipment.strategy.label}</strong><p>${shipment.strategy.reason}</p></div>`+el.innerHTML;
}
function renderSecuringRecommendation(){const el=$('securingRecommendation'),panel=$('securingPanel'),plan=result.securing;if(!plan||(!plan.dunnage.length&&!plan.airbags.length&&!plan.reviews.length)){panel.hidden=true;el.innerHTML='';return}panel.hidden=false;panel.open=false;const beam=plan.dunnage.find(d=>d.kind==='beam'),chocks=plan.dunnage.filter(d=>d.kind!=='beam'),profile=TRANSPORT_PROFILES[plan.transportMode]||TRANSPORT_PROFILES.combined,reviewUnits=plan.reviews.reduce((sum,w)=>sum+(w.count||1),0),items=[...(beam?[`<div><strong>문쪽 전면 가로 각재</strong>노출 화물 폭 ${(beam.w/1000).toFixed(2)}m 전체 지지</div>`]:[]),...chocks.map((d,i)=>`<div><strong>각재 지지 부목 ${i+1}/${chocks.length}</strong>Y ${(d.y/1000).toFixed(2)}m · 바닥 고정은 현장 확인</div>`),...plan.airbags.slice(0,8).map((a,i)=>`<div><strong>에어백 ${i+1} · ${a.location}</strong>X ${(a.x/1000).toFixed(2)}m · Y ${(a.y/1000).toFixed(2)}m · Z ${(a.z/1000).toFixed(2)}m</div>`),...plan.reviews.map(w=>`<div><strong>${w.severity==='rearrange'?'배치 재검토':'현장 고정 검토'} · ${esc(w.product)}${w.count>1?` × ${w.count}`:''}</strong>${w.location}${w.axes?` · 미지지 ${w.axes}`:''}</div>`)];$('securingCount').textContent=`${profile.label} · 부목 ${chocks.length} · 에어백 ${plan.airbags.length}${plan.reviews.length?` · 안정성 검토 ${plan.reviews.length}유형/${reviewUnits}개`:''}`;el.innerHTML=`<h3>컨테이너 ${result.containerNumber} · ${profile.label} 운송 안정성</h3><p>자동 밴드 수량과 경로는 제시하지 않습니다. ${profile.label} 운송에서 피칭·롤링·히빙 또는 가감속에 불리한 높은 적층, 측면 간극, 문측 노출과 원통 구름 위험을 선별합니다.</p><div class="securing-items">${items.join('')}</div>`}
function setStep(step){if(!result)return;visibleStep=Math.max(0,Math.min(result.placed.length,step));$('currentStep').textContent=visibleStep;$('stepRange').value=visibleStep;$('prevStep').disabled=visibleStep===0;$('nextStep').disabled=visibleStep===result.placed.length;draw()}
function togglePlayback(){if(playTimer){stopPlayback();return}if(visibleStep>=result.placed.length)setStep(0);$('playSteps').textContent='Ⅱ';playTimer=setInterval(()=>{if(visibleStep>=result.placed.length){stopPlayback();return}setStep(visibleStep+1)},650)}
function stopPlayback(){if(playTimer)clearInterval(playTimer);playTimer=null;if($('playSteps'))$('playSteps').textContent='▶'}

function resizeCanvas(){const c=$('loadingCanvas'),rect=$('canvasWrap').getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1);c.width=Math.max(1,rect.width*dpr);c.height=Math.max(1,rect.height*dpr);if(threeView&&rect.width&&rect.height){threeView.renderer.setSize(rect.width,rect.height,false);threeView.camera.aspect=rect.width/rect.height;threeView.camera.updateProjectionMatrix()}draw()}
function draw(){if(!result){clearDrawing();return}if(typeof THREE!=='undefined'){drawThree();return}const canvas=$('loadingCanvas'),ctx=canvas.getContext('2d'),dpr=Math.min(2,window.devicePixelRatio||1),W=canvas.width/dpr,H=canvas.height/dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,W,H);if(viewMode==='top')drawTop(ctx,W,H);else drawIso(ctx,W,H)}
function initThree(){
  if(threeView||typeof THREE==='undefined')return;const mount=$('threeMount');mount.style.display='block';const rect=$('canvasWrap').getBoundingClientRect(),renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(2,window.devicePixelRatio||1));renderer.setSize(rect.width,rect.height,false);renderer.outputColorSpace=THREE.SRGBColorSpace;mount.appendChild(renderer.domElement);$('loadingCanvas').style.display='none';
  const scene=new THREE.Scene(),camera3=new THREE.PerspectiveCamera(34,rect.width/rect.height,1,100000),group=new THREE.Group();scene.add(group);scene.add(new THREE.HemisphereLight(0xffffff,0x789085,2.1));const light=new THREE.DirectionalLight(0xffffff,2.6);light.position.set(-6000,8000,5000);scene.add(light);threeView={renderer,scene,camera:camera3,group};
  let dragging=false,lastX=0,lastY=0;const el=renderer.domElement;el.addEventListener('pointerdown',e=>{if(viewMode!=='iso')return;dragging=true;lastX=e.clientX;lastY=e.clientY;el.setPointerCapture(e.pointerId)});el.addEventListener('pointermove',e=>{if(!dragging)return;camera.yaw+=(e.clientX-lastX)*.008;camera.pitch=Math.max(.12,Math.min(1.35,camera.pitch-(e.clientY-lastY)*.006));lastX=e.clientX;lastY=e.clientY;drawThree()});el.addEventListener('pointerup',()=>dragging=false);el.addEventListener('wheel',e=>{e.preventDefault();camera.zoom=Math.max(.55,Math.min(2,camera.zoom*(e.deltaY>0?.9:1.1)));drawThree()},{passive:false});
}
function disposeThreeGroup(){if(!threeView)return;while(threeView.group.children.length){const o=threeView.group.children.pop();o.geometry?.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material?.dispose();o.children?.forEach(c=>{c.geometry?.dispose();c.material?.dispose()})}}
function clearDrawing(){if(threeView){disposeThreeGroup();threeView.renderer.dispose();threeView.renderer.domElement.remove();threeView=null}$('threeMount').style.display='none';const canvas=$('loadingCanvas'),ctx=canvas.getContext('2d');canvas.style.display='block';ctx.clearRect(0,0,canvas.width,canvas.height)}
function drawThree(){
  initThree();if(!threeView)return;const {renderer,scene,camera:cam,group}=threeView,c=result.container;disposeThreeGroup();
  const visible=result.placed.slice(0,visibleStep),toColor=hex=>new THREE.Color(hex),edgeMat=new THREE.LineBasicMaterial({color:0x315e4c,transparent:true,opacity:.65});
  visible.forEach(p=>{let geometry;if(p.shape==='cylinder'){geometry=new THREE.CylinderGeometry(.5,.5,1,28);geometry.scale(p.l,p.h,p.w)}else geometry=new THREE.BoxGeometry(p.l,p.h,p.w);const material=new THREE.MeshStandardMaterial({color:toColor(p.color),roughness:.72,metalness:.03,transparent:true,opacity:showCog?.2:.94,depthWrite:!showCog,side:THREE.DoubleSide}),mesh=new THREE.Mesh(geometry,material);mesh.position.set(p.x+p.l/2,p.z+p.h/2,p.y+p.w/2);group.add(mesh);const edges=new THREE.LineSegments(new THREE.EdgesGeometry(geometry),new THREE.LineBasicMaterial({color:0x263b32,transparent:true,opacity:showCog?.12:.42}));edges.position.copy(mesh.position);group.add(edges)});
  if(visibleStep===result.placed.length&&result.securing){
    const woodMaterial=new THREE.MeshStandardMaterial({color:0xa56a32,roughness:.88}),nailMaterial=new THREE.MeshStandardMaterial({color:0x383d42,metalness:.65,roughness:.38});
    if(showDunnage)result.securing.dunnage.forEach(d=>{
      if(d.kind==='beam'){const geometry=new THREE.BoxGeometry(d.l,d.h,d.w),mesh=new THREE.Mesh(geometry,woodMaterial);mesh.position.set(d.x+d.l/2,d.h/2,d.y+d.w/2);group.add(mesh);const edges=new THREE.LineSegments(new THREE.EdgesGeometry(geometry),new THREE.LineBasicMaterial({color:0x62401f,transparent:true,opacity:.7}));edges.position.copy(mesh.position);group.add(edges);return}
      const dx=d.l,dz=d.w,h=d.h,isX=d.axis==='x',highAtMax=d.side==='min',positions=isX
        ?[0,0,0, dx,0,0, dx,0,dz, 0,0,dz, highAtMax?dx:0,h,0, highAtMax?dx:0,h,dz]
        :[0,0,0, dx,0,0, dx,0,dz, 0,0,dz, 0,h,highAtMax?dz:0, dx,h,highAtMax?dz:0],
        indices=highAtMax
          ?(isX?[0,2,1,0,3,2,1,2,5,1,5,4,0,4,5,0,5,3,0,1,4,3,5,2]:[0,2,1,0,3,2,3,5,2,3,4,5,0,1,5,0,5,4,0,4,3,1,2,5])
          :(isX?[0,2,1,0,3,2,0,4,5,0,5,3,1,2,5,1,5,4,0,1,4,3,5,2]:[0,2,1,0,3,2,0,1,5,0,5,4,3,4,5,3,5,2,0,4,3,1,2,5]);
      const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geometry.setIndex(indices);geometry.computeVertexNormals();
      const mesh=new THREE.Mesh(geometry,woodMaterial);mesh.position.set(d.x,4,d.y);group.add(mesh);
      const nailGeometry=new THREE.CylinderGeometry(12,12,8,14);
      [0.3,0.7].forEach(t=>{const nail=new THREE.Mesh(nailGeometry,nailMaterial);nail.position.set(d.x+(isX?(highAtMax?.2:.8)*dx:t*dx),10,d.y+(isX?t*dz:(highAtMax?.2:.8)*dz));group.add(nail)});
    });
    if(showAirbags)result.securing.airbags.forEach(a=>{
      const material=new THREE.MeshStandardMaterial({color:0x70bde9,transparent:true,opacity:.74,roughness:.58}),geometry=new THREE.SphereGeometry(.5,28,18),mesh=new THREE.Mesh(geometry,material);
      mesh.scale.set(a.l*.94,a.h,a.w*.94);mesh.position.set(a.x+a.l/2,a.z+a.h/2,a.y+a.w/2);group.add(mesh);
      const seam=new THREE.Mesh(new THREE.TorusGeometry(.5,0.018,8,36),new THREE.MeshStandardMaterial({color:0xd7effb,transparent:true,opacity:.8,roughness:.65}));seam.scale.set(a.l*.96,a.w*.96,1);seam.rotation.x=Math.PI/2;seam.position.set(a.x+a.l/2,a.z+a.h/2,a.y+a.w/2);group.add(seam);
      const valve=new THREE.Mesh(new THREE.CylinderGeometry(17,21,28,12),new THREE.MeshStandardMaterial({color:0x276e96,roughness:.48}));valve.position.set(a.x+a.l/2,a.z+a.h+8,a.y+a.w/2);group.add(valve);
    });
  }
  const frameGeo=new THREE.BoxGeometry(c.l,c.h,c.w),frame=new THREE.LineSegments(new THREE.EdgesGeometry(frameGeo),edgeMat);frame.position.set(c.l/2,c.h/2,c.w/2);group.add(frame);
  const doorGeo=new THREE.BoxGeometry(10,c.h,c.w),doorFrame=new THREE.LineSegments(new THREE.EdgesGeometry(doorGeo),new THREE.LineBasicMaterial({color:0x0066cc,transparent:true,opacity:.95}));doorFrame.position.set(0,c.h/2,c.w/2);group.add(doorFrame);
  const floorGeo=new THREE.PlaneGeometry(c.l,c.w),floor=new THREE.Mesh(floorGeo,new THREE.MeshStandardMaterial({color:0xdfe9e2,transparent:true,opacity:.22,side:THREE.DoubleSide}));floor.rotation.x=-Math.PI/2;floor.position.set(c.l/2,0,c.w/2);group.add(floor);
  const balance=LoadwiseInsights.balance(result);if(showCog&&balance){const color=balance.level==='safe'?0x16803c:balance.level==='caution'?0xd38b00:0xb42318,marker=new THREE.Mesh(new THREE.SphereGeometry(140,24,18),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.3,depthTest:false}));marker.position.set(balance.cog.x,balance.cog.z,balance.cog.y);marker.renderOrder=10;group.add(marker);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(balance.cog.x,0,balance.cog.y),marker.position]),new THREE.LineDashedMaterial({color,dashSize:70,gapSize:35,depthTest:false}));line.computeLineDistances();line.renderOrder=9;group.add(line);const ring=new THREE.Mesh(new THREE.RingGeometry(150,195,32),new THREE.MeshBasicMaterial({color,side:THREE.DoubleSide,transparent:true,opacity:.95,depthTest:false}));ring.rotation.x=-Math.PI/2;ring.position.set(balance.cog.x,6,balance.cog.y);ring.renderOrder=9;group.add(ring)}
  const target=new THREE.Vector3(c.l/2,c.h*.42,c.w/2),distance=Math.max(c.l,c.w*2.5,c.h*2.5)*1.25/camera.zoom;
  if(viewMode==='top'){cam.position.set(c.l/2,distance*1.1,c.w/2+.01);cam.up.set(0,0,-1)}else if(viewMode==='door'){cam.position.set(-distance*.72,c.h*.45,c.w/2);cam.up.set(0,1,0)}else if(viewMode==='left'){cam.position.set(c.l/2,c.h*.45,-distance*.72);cam.up.set(0,1,0)}else if(viewMode==='right'){cam.position.set(c.l/2,c.h*.45,c.w+distance*.72);cam.up.set(0,1,0)}else{const horizontal=distance*Math.cos(camera.pitch);cam.position.set(target.x+Math.cos(camera.yaw)*horizontal,target.y+Math.sin(camera.pitch)*distance,target.z+Math.sin(camera.yaw)*horizontal);cam.up.set(0,1,0)}cam.lookAt(target);cam.near=Math.max(1,distance/1000);cam.far=distance*10;cam.updateProjectionMatrix();renderer.render(scene,cam);
}
function drawIso(ctx,W,H){
  const c=result.container,cy=Math.cos(camera.yaw),sy=Math.sin(camera.yaw),cp=Math.cos(camera.pitch),sp=Math.sin(camera.pitch);
  const raw=(x,y,z)=>{x-=c.l/2;y-=c.w/2;z-=c.h/2;const rx=x*cy-y*sy,ry=x*sy+y*cy;return[rx,ry*sp-z*cp,ry*cp+z*sp]};
  const corners=[[0,0,0],[c.l,0,0],[0,c.w,0],[c.l,c.w,0],[0,0,c.h],[c.l,0,c.h],[0,c.w,c.h],[c.l,c.w,c.h]],rawCorners=corners.map(v=>raw(...v));
  const xs=rawCorners.map(p=>p[0]),ys=rawCorners.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),pad=58;
  const scale=Math.min((W-pad*2)/(maxX-minX),(H-pad*2)/(maxY-minY))*camera.zoom,centerX=(minX+maxX)/2,centerY=(minY+maxY)/2;
  const P=(x,y,z)=>{const p=raw(x,y,z);return[W/2+(p[0]-centerX)*scale,H/2+(p[1]-centerY)*scale,p[2]]};
  const visible=result.placed.slice(0,visibleStep),polygons=[];
  const addBox=o=>{const pts=[[o.x,o.y,o.z],[o.x+o.l,o.y,o.z],[o.x,o.y+o.w,o.z],[o.x+o.l,o.y+o.w,o.z],[o.x,o.y,o.z+o.h],[o.x+o.l,o.y,o.z+o.h],[o.x,o.y+o.w,o.z+o.h],[o.x+o.l,o.y+o.w,o.z+o.h]].map(v=>P(...v));const faces=[[0,1,3,2],[4,6,7,5],[0,4,5,1],[2,3,7,6],[0,2,6,4],[1,5,7,3]],tones=[-18,20,-7,5,-12,1];faces.forEach((f,i)=>polygons.push({pts:f.map(n=>pts[n]),depth:f.reduce((s,n)=>s+pts[n][2],0)/4,fill:shade(o.color,tones[i]),stroke:'rgba(19,37,29,.34)'}))};
  const addCylinder=o=>{const n=20,cx=o.x+o.l/2,midY=o.y+o.w/2,rx=o.l/2,ry=o.w/2,b=[],t=[];for(let i=0;i<n;i++){const a=Math.PI*2*i/n;b.push(P(cx+Math.cos(a)*rx,midY+Math.sin(a)*ry,o.z));t.push(P(cx+Math.cos(a)*rx,midY+Math.sin(a)*ry,o.z+o.h))}for(let i=0;i<n;i++){const j=(i+1)%n,pts=[b[i],b[j],t[j],t[i]];polygons.push({pts,depth:pts.reduce((s,p)=>s+p[2],0)/4,fill:shade(o.color,i%2?-3:3),stroke:'rgba(19,37,29,.24)'})}polygons.push({pts:b,depth:b.reduce((s,p)=>s+p[2],0)/n,fill:shade(o.color,-14),stroke:'rgba(19,37,29,.3)'});polygons.push({pts:t,depth:t.reduce((s,p)=>s+p[2],0)/n,fill:shade(o.color,20),stroke:'rgba(19,37,29,.35)'})};
  visible.forEach(p=>p.shape==='cylinder'?addCylinder(p):addBox(p));
  polygons.sort((a,b)=>a.depth-b.depth).forEach(poly=>{ctx.beginPath();poly.pts.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.fillStyle=poly.fill;ctx.globalAlpha=.94;ctx.fill();ctx.strokeStyle=poly.stroke;ctx.lineWidth=.7;ctx.stroke()});ctx.globalAlpha=1;
  const framePts=corners.map(v=>P(...v)),edges=[[0,1],[0,2],[0,4],[1,3],[1,5],[2,3],[2,6],[3,7],[4,5],[4,6],[5,7],[6,7]];ctx.strokeStyle='rgba(15,107,72,.72)';ctx.lineWidth=1.4;ctx.setLineDash([5,4]);edges.forEach(([a,b])=>{ctx.beginPath();ctx.moveTo(framePts[a][0],framePts[a][1]);ctx.lineTo(framePts[b][0],framePts[b][1]);ctx.stroke()});ctx.setLineDash([]);
  if(visible.length){const p=visible[visible.length-1],[x,y]=P(p.x+p.l/2,p.y+p.w/2,p.z+p.h);ctx.fillStyle='#13251d';ctx.beginPath();ctx.arc(x,y-15,12,0,Math.PI*2);ctx.fill();ctx.fillStyle='#c9ff5a';ctx.font='700 10px DM Sans';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(p.order),x,y-15);ctx.textAlign='start';ctx.textBaseline='alphabetic'}
}
function drawTop(ctx,W,H){const c=result.container,pad=52,scale=Math.min((W-pad*2)/c.l,(H-pad*2)/c.w)*camera.zoom,ox=(W-c.l*scale)/2,oy=(H-c.w*scale)/2;ctx.fillStyle='#f7faf6';ctx.strokeStyle='rgba(15,107,72,.7)';ctx.lineWidth=2;ctx.fillRect(ox,oy,c.l*scale,c.w*scale);ctx.strokeRect(ox,oy,c.l*scale,c.w*scale);result.placed.slice(0,visibleStep).sort((a,b)=>a.z-b.z).forEach(p=>{ctx.fillStyle=p.color+'d9';ctx.strokeStyle='rgba(19,37,29,.35)';ctx.beginPath();if(p.shape==='cylinder')ctx.ellipse(ox+(p.x+p.l/2)*scale,oy+(p.y+p.w/2)*scale,p.l*scale/2,p.w*scale/2,0,0,Math.PI*2);else ctx.rect(ox+p.x*scale,oy+p.y*scale,p.l*scale,p.w*scale);ctx.fill();ctx.stroke();if(p.l*scale>28&&p.w*scale>18){ctx.fillStyle='white';ctx.font='700 10px DM Sans';ctx.fillText(p.order,ox+p.x*scale+5,oy+p.y*scale+13)}})}
function shade(hex,amt){const n=parseInt(hex.slice(1),16),r=Math.max(0,Math.min(255,(n>>16)+amt)),g=Math.max(0,Math.min(255,((n>>8)&255)+amt)),b=Math.max(0,Math.min(255,(n&255)+amt));return`rgb(${r},${g},${b})`}
function setView(mode){viewMode=mode;for(const name of ['Iso','Top','Door','Left','Right'])$(`view${name}`).classList.toggle('active',mode===name.toLowerCase());$('canvasHint').textContent=mode==='iso'?'드래그하여 회전 · 휠로 확대/축소':'고정 시점 · 휠로 확대/축소';draw()}
function toggleCenterOfGravity(){showCog=!showCog;const button=$('viewCog');button.classList.toggle('active',showCog);button.setAttribute('aria-pressed',String(showCog));draw()}
function toggleSecuringVisibility(type){const active=type==='dunnage'?(showDunnage=!showDunnage):(showAirbags=!showAirbags),button=$(type==='dunnage'?'toggleDunnage':'toggleAirbags');button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));button.querySelector('b').textContent=active?'ON':'OFF';draw()}

async function readFile(file){if(!file)return;try{let rows;if(file.name.toLowerCase().endsWith('.csv'))rows=parseCSV(await file.text());else{if(typeof XLSX==='undefined')throw new Error('Excel 파서를 불러오지 못했습니다. 인터넷 연결을 확인하거나 CSV를 사용해 주세요.');const wb=XLSX.read(await file.arrayBuffer()),sheet=wb.Sheets[wb.SheetNames[0]];rows=XLSX.utils.sheet_to_json(sheet,{defval:''})}const mapped=rows.map((r,i)=>mapRow(r,i)).filter(Boolean);if(!mapped.length)throw new Error('인식 가능한 제품 데이터가 없습니다. 열 이름을 확인해 주세요.');products=mapped;renderProducts();window.loadwiseStorage?.suggestName(file.name.replace(/\.[^.]+$/,''));switchTab('manual');if(await showAppMessage(`${mapped.length}개 품목을 불러왔습니다.\n바로 시뮬레이션을 진행할까요?`,{title:'파일 불러오기 완료',tone:'success',confirmAction:true,actionLabel:'시뮬레이션 실행',cancelLabel:'불러오기만'}))await simulate()}catch(e){showAppMessage(e.message,{title:'파일을 불러오지 못했습니다',tone:'error'})}}
function parseFlag(value,label,row){const v=String(value).trim().toLowerCase();if(['yes','true','1','예','허용'].includes(v))return true;if(['no','false','0','아니오','금지'].includes(v))return false;throw new Error(`${row}행 ${label}은 yes/no, 예/아니오, true/false, 1/0 중 하나여야 합니다.`)}
function mapRow(r,i){const row=i+2,get=(...keys)=>{const key=Object.keys(r).find(k=>keys.some(x=>k.toLowerCase().replace(/\s/g,'')===x));return key?r[key]:''},shape=String(get('형상','제품형상','shape')).trim().toLowerCase(),qty=Number(get('수량','qty','quantity')),topRaw=get('상부허용하중','상부허용하중(kg)','maxtopload','maxtopload(kg)'),maxTopLoadKg=topRaw===''?null:Number(topRaw),values={l:Number(get('길이','길이(mm)','length','length(mm)')),w:Number(get('너비','폭','너비(mm)','width','width(mm)')),h:Number(get('높이','높이(mm)','height','height(mm)')),weight:Number(get('중량','중량(kg)','weight','weight(kg)'))},name=String(get('제품명','name','product')).trim();if(!name)throw new Error(`${row}행 제품명이 비어 있습니다.`);if(!['박스형','box','원통형','cylinder'].includes(shape))throw new Error(`${row}행 형상은 박스형 또는 원통형이어야 합니다.`);if(Object.values(values).some(v=>!Number.isFinite(v)||v<=0))throw new Error(`${row}행 치수와 중량은 0보다 큰 숫자여야 합니다.`);if(!Number.isInteger(qty)||qty<=0)throw new Error(`${row}행 수량은 1 이상의 정수여야 합니다.`);if(maxTopLoadKg!=null&&(!Number.isFinite(maxTopLoadKg)||maxTopLoadKg<0))throw new Error(`${row}행 상부 허용하중은 0 이상의 숫자이거나 빈 값이어야 합니다.`);return{name,group:get('제품군','group','category')||'기타',shape:shape==='원통형'||shape==='cylinder'?'cylinder':'box',...values,maxTopLoadKg,qty,rotate:parseFlag(get('눕힘허용','눕혀서적재가능','회전허용','rotation'),'눕힘허용',row),fragile:parseFlag(get('상부적재금지','fragile'),'상부적재금지',row),id:Date.now()+i,color:COLORS[i%COLORS.length]}}
function parseCSV(text){const rows=[],cells=splitCSV(text.replace(/^\uFEFF/,''));let row=[];for(const cell of cells){if(cell===null){if(row.some(v=>v!==''))rows.push(row);row=[]}else row.push(cell.trim())}if(row.some(v=>v!==''))rows.push(row);const heads=rows.shift()||[];return rows.map(values=>Object.fromEntries(heads.map((h,i)=>[h,values[i]||''])))}
function splitCSV(text){let out=[],cur='',q=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'&&text[i+1]==='"'){cur+='"';i++}else if(ch==='"')q=!q;else if(ch===','&&!q){out.push(cur);cur=''}else if((ch==='\n'||ch==='\r')&&!q){out.push(cur);out.push(null);cur='';if(ch==='\r'&&text[i+1]==='\n')i++}else cur+=ch}if(q)throw new Error('CSV 따옴표가 닫히지 않았습니다.');out.push(cur);return out}
function downloadTemplate(){download('loadspace-template.csv','\uFEFF제품명,제품군,형상,길이(mm),너비(mm),높이(mm),중량(kg),상부허용하중(kg),수량,눕힘허용,상부적재금지\n산업용 펌프,기계류,박스형,1200,800,900,420,1500,4,yes,no\n케이블 드럼,부품,원통형,900,900,700,310,,6,no,no')}
async function captureView(mode){const previous=viewMode;setView(mode);await new Promise(resolve=>requestAnimationFrame(resolve));const source=threeView?.renderer?.domElement||$('loadingCanvas'),image=source.toDataURL('image/png');setView(previous);return image}
async function exportPdf(){
  if(!shipment)return;if(shipment.unallocated.length){showAppMessage(`미배치 화물 ${shipment.unallocated.length}개를 해결한 후 작업지시서를 만들 수 있습니다.`,{title:'PDF 작업지시서가 제한됩니다',tone:'warning'});return}const printWindow=window.open('','loadwise-work-instruction');if(!printWindow){showAppMessage('작업지시서 새 창을 열 수 없습니다. 브라우저의 팝업 차단을 해제해 주세요.',{title:'새 창이 차단되었습니다',tone:'warning'});return}printWindow.document.write('<!doctype html><title>작업지시서 준비 중</title><p style="font-family:sans-serif;padding:24px">작업지시서를 준비하고 있습니다…</p>');
  const outcome=shipmentOutcome(shipment),balance=LoadwiseInsights.ctu(result),validation=LoadwiseValidator.validateLoad(result,{minSupport:shipment.priority==='volume'?.7:1}),compression=validation.metrics,iso=await captureView('iso'),top=await captureView('top'),door=await captureView('door'),plan=result.placed.map(p=>`<tr><td>${p.order}</td><td>${esc(p.name)}</td><td>${p.unit}</td><td>${p.l}×${p.w}×${p.h}</td><td>${p.weight.toLocaleString()} kg</td></tr>`).join(''),transport=TRANSPORT_PROFILES[result.securing?.transportMode]||TRANSPORT_PROFILES.combined,fixedSummary=`${transport.label} 운송 · 부목 ${result.securing?.dunnage.length||0}개 · 에어백 ${result.securing?.airbags.length||0}개 · 안정성 검토 ${result.securing?.reviews.length||0}건`;
  const report=`<header><div><small>LOADWISE WORK INSTRUCTION</small><h1>${esc($('projectName').value||'적재 계획')}</h1></div><b>${new Date().toLocaleDateString('ko-KR')}</b></header><section class="report-summary"><div><span>컨테이너</span><b>${esc(result.container.name)} · ${activeContainer+1}/${shipment.containers.length}</b></div><div><span>적재 결과</span><b>${outcome.loaded}/${outcome.total}개</b></div><div><span>공간 / 중량</span><b>${result.volumeRate.toFixed(1)}% / ${result.weightRate.toFixed(1)}%</b></div><div><span>총중량</span><b>${result.totalWeight.toLocaleString()} kg</b></div></section><section><h2>적재 시점</h2><div class="report-images"><figure><img src="${iso}"><figcaption>3D 전체</figcaption></figure><figure><img src="${top}"><figcaption>상면</figcaption></figure><figure><img src="${door}"><figcaption>문 입구</figcaption></figure></div></section><section><h2>CTU 중량배분 사전검사와 고정재</h2><div class="report-metrics"><span>문쪽 / 안쪽<b>${balance.door.toFixed(1)} / ${balance.rear.toFixed(1)}%</b></span><span>좌측 / 우측<b>${balance.left.toFixed(1)} / ${balance.right.toFixed(1)}%</b></span><span>중심 편차<b>${Math.abs(balance.xOffset).toFixed(1)} / ${Math.abs(balance.yOffset).toFixed(1)}%</b></span><span>50% 길이 최대 질량<b>${balance.concentration.toFixed(1)}%</b></span><span>수직 무게중심<b>높이의 ${balance.vertical.toFixed(1)}%</b></span><span>압축하중<b>${compression.compressionVerified}개 검증 · ${compression.compressionUnverified}개 미입력</b></span></div><p><strong>고정재 목록:</strong> ${fixedSummary}. 상세 위치는 3D 화면과 Excel 계획의 고정재 시트를 확인하세요.</p></section><section><h2>적재 순서</h2><table><thead><tr><th>순서</th><th>제품</th><th>번호</th><th>배치 크기(mm)</th><th>중량</th></tr></thead><tbody>${plan}</tbody></table></section><section class="field-record"><h2>현장 작업 기록</h2><div><span>실제 적재 수량<strong></strong></span><span>실제 컨테이너 수<strong></strong></span><span>추가 고정재<strong></strong></span></div><p>변경·파손·특이사항</p><i></i><i></i></section><footer><p><strong>안전 고지</strong> 본 문서는 작업 검토용입니다. 상부 허용하중 미입력 화물, 축하중, 바닥 집중하중, 마찰·동하중과 래싱 용량은 별도 확인해야 합니다.</p><div>현장 확인자 ____________________ &nbsp; 날짜 ____________________</div></footer>`;
  const css=`@page{size:A4 portrait;margin:10mm}*{box-sizing:border-box}body{margin:0;background:#f5f5f7;color:#1d1d1f;font:12px/1.45 Arial,"Noto Sans KR",sans-serif}.toolbar{position:sticky;top:0;display:flex;justify-content:flex-end;gap:8px;padding:12px calc((100% - 190mm)/2);background:#111;z-index:2}.toolbar button{border:0;border-radius:999px;padding:9px 16px;font-weight:700;cursor:pointer}.toolbar .primary{background:#0878d1;color:#fff}main{width:210mm;min-height:297mm;margin:20px auto;padding:10mm;background:#fff;box-shadow:0 8px 30px #0002}header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #1d1d1f;padding-bottom:8px}h1{margin:3px 0 0;font-size:24px}h2{margin:16px 0 7px;font-size:15px}.report-summary,.report-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:9px}.report-metrics{grid-template-columns:repeat(3,1fr)}.report-summary div,.report-metrics span{padding:8px;border:1px solid #ddd;border-radius:6px}.report-summary span,.report-metrics span{color:#666}.report-summary b,.report-metrics b{display:block;margin-top:3px;color:#111}.report-images{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.report-images figure{margin:0;border:1px solid #ddd}.report-images img{display:block;width:100%;height:120px;object-fit:contain}.report-images figcaption{padding:4px;text-align:center}table{width:100%;border-collapse:collapse;font-size:10px}th,td{padding:4px 6px;border:1px solid #ddd;text-align:left}thead{display:table-header-group}.field-record{break-inside:avoid}.field-record>div{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.field-record span{padding:8px;border:1px solid #bbb}.field-record strong{display:block;height:22px}.field-record p{margin:12px 0 3px}.field-record i{display:block;height:26px;border-bottom:1px solid #aaa}footer{display:block;margin-top:16px;border-top:1px solid #333;padding-top:9px}footer div{margin-top:16px;text-align:right}section{break-inside:avoid}@media print{body{background:#fff}.toolbar{display:none}main{width:auto;min-height:0;margin:0;padding:0;box-shadow:none}}`;
  printWindow.document.open();printWindow.document.write(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${esc($('projectName').value||'적재 계획')} · 작업지시서</title><style>${css}</style></head><body><nav class="toolbar"><button id="closePrint">창 닫기</button><button class="primary" id="startPrint">인쇄 / PDF 저장</button></nav><main>${report}</main></body></html>`);printWindow.document.close();printWindow.document.getElementById('startPrint').onclick=()=>printWindow.print();printWindow.document.getElementById('closePrint').onclick=()=>printWindow.close();printWindow.focus()
}
function exportPlan(){
  if(!result)return;
  if(shipment?.unallocated.length){showAppMessage(`미배치 화물 ${shipment.unallocated.length}개가 남아 있습니다. 입력 조건을 수정하고 다시 계산한 뒤 내보내 주세요.`,{title:'Excel 내보내기가 제한됩니다',tone:'warning'});return}
  if(typeof XLSX==='undefined'){showAppMessage('Excel 내보내기 모듈을 불러오지 못했습니다. 연결 상태를 확인한 뒤 다시 시도해 주세요.',{title:'Excel 내보내기 오류',tone:'error'});return}
  const loads=shipment?shipment.containers:[result],plan=[],summary=[],securing=[];
  loads.forEach((load,i)=>{
    const balance=LoadwiseInsights.ctu(load),validation=LoadwiseValidator.validateLoad(load,{minSupport:shipment?.priority==='volume'?.7:1}),compression=validation.metrics,transport=TRANSPORT_PROFILES[load.securing?.transportMode]||TRANSPORT_PROFILES.combined;summary.push({'컨테이너 번호':i+1,'컨테이너 규격':load.container.name,'운송모드':transport.label,'적재 전략':shipment?.strategy?.label||'사용자 선택','선택 근거':shipment?.strategy?.reason||'','적재 수량':load.placed.length,'총 중량(kg)':load.totalWeight,'공간 활용률(%)':Number(load.volumeRate.toFixed(1)),'중량 활용률(%)':Number(load.weightRate.toFixed(1)),'문쪽 중량배분(%)':Number(balance.door.toFixed(1)),'안쪽 중량배분(%)':Number(balance.rear.toFixed(1)),'좌측 중량배분(%)':Number(balance.left.toFixed(1)),'우측 중량배분(%)':Number(balance.right.toFixed(1)),'무게중심 X(mm)':Math.round(balance.cog.x),'무게중심 Y(mm)':Math.round(balance.cog.y),'무게중심 Z(mm)':Math.round(balance.cog.z),'50% 길이 최대 질량(%)':Number(balance.concentration.toFixed(1)),'수직 무게중심(높이%)':Number(balance.vertical.toFixed(1)),'압축하중 검증 화물':compression.compressionVerified,'압축하중 미입력 화물':compression.compressionUnverified,'CTU 사전검사':balance.level==='safe'?'안정':balance.level==='caution'?'주의':'위험'});
    load.placed.forEach(p=>plan.push({'컨테이너 번호':i+1,'컨테이너 규격':load.container.name,'적재 순서':p.order,'제품명':p.name,'제품군':p.group,'제품 번호':p.unit,'제품 형상':p.shape==='cylinder'?'원통형':'박스형','문에서 안쪽 X(mm)':p.x,'좌측에서 우측 Y(mm)':p.y,'바닥에서 위 Z(mm)':p.z,'배치 길이(mm)':p.l,'배치 너비(mm)':p.w,'배치 높이(mm)':p.h,'개당 중량(kg)':p.weight}));
    const fixed=[...(load.securing?.dunnage||[]),...(load.securing?.airbags||[])];fixed.forEach((f,n)=>securing.push({'컨테이너 번호':i+1,'번호':n+1,'구분':f.type==='dunnage'?(f.kind==='beam'?'가로 각재':'부목'):'에어백','추천 위치':f.location||'화물 간극','관련 제품':f.product||'','X(mm)':Math.round(f.x),'Y(mm)':Math.round(f.y),'Z(mm)':Math.round(f.z),'길이(mm)':Math.round(f.l),'너비(mm)':Math.round(f.w),'높이(mm)':Math.round(f.h)}));(load.securing?.reviews||[]).forEach((review,n)=>securing.push({'컨테이너 번호':i+1,'번호':fixed.length+n+1,'구분':review.severity==='rearrange'?'배치 재검토':'현장 고정 검토','추천 위치':review.location,'관련 제품':review.product,'미지지 방향':review.axes||''}));
  });
  const productRows=products.map(p=>({'제품명':p.name,'제품군':p.group,'제품 형상':p.shape==='cylinder'?'원통형':'박스형','수량':p.qty,'길이(mm)':p.l,'너비(mm)':p.w,'높이(mm)':p.h,'개당 중량(kg)':p.weight,'상부 허용하중(kg)':Number.isFinite(p.maxTopLoadKg)?p.maxTopLoadKg:'미입력','눕힘 허용':p.rotate?'예':'아니오','상부 적재 금지':p.fragile?'예':'아니오'}));
  const wb=XLSX.utils.book_new();
  const notice=[{'구분':'사용 한계','내용':'본 결과는 작업 검토용 베타입니다. 전역 최적해, 압축강도, 축하중, 위험물 규정을 보장하지 않습니다.'},{'구분':'현장 검증','내용':'실제 적재 전 전문가가 화물 강도, 중량중심, 고정재, 운송 규정을 확인해야 합니다.'}];[['요약',summary],['적재계획',plan],['제품목록',productRows],['고정재',securing],['안전고지',notice]].forEach(([name,rows])=>{const ws=XLSX.utils.json_to_sheet(rows.length?rows:[{'내용':'해당 항목 없음'}]);ws['!cols']=Object.keys(rows[0]||{'내용':''}).map(k=>({wch:Math.max(12,Math.min(48,k.length*2+4))}));XLSX.utils.book_append_sheet(wb,ws,name)});
  XLSX.writeFile(wb,'loadspace-loading-plan.xlsx');
}
function csvCell(v){v=String(v);return /[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v}function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
if(typeof document!=='undefined')init();
